### ISSUE TITLE
en120102 textures not exporting

### ISSUE THREAD

**Issue by nanogram** [ScanMountGoat/xenoblade_blender#61]
When importing en120102(xcde) to blender(plugin v0.15.4), exporting as glb, and then reimporting, only the jawa rider loses his textures.
 
![image](https://github.com/user-attachments/assets/64ee3a55-cacc-47fe-bcfb-d4d4be4c9205)
![image](https://github.com/user-attachments/assets/7de37239-2bd2-4d7e-89ff-e0df0be4ee42)

**Comment by ScanMountGoat** [comment]
The glTF/glb exporter in Blender only supports very basic material node setups due to limitations in the glTF format itself. I don't know of any formats that would reliably preserve the texture layering when importing into other applications. If you just need the basic textures, I would export using xc3_gltf instead.
